### ISSUE TITLE
How i can download dependencies?

### ISSUE THREAD

**Issue by IZ44KPvP** [dularion/streama-video-player#1]
I Not have experience in this area but i know that is missing some components to work
Example:
 <script src="../bower_components/angular/angular.js"></script>
  <script src="../bower_components/angular-translate/angular-translate.js"></script>
  <script src="../bower_components/jquery/dist/jquery.js"></script>
  <script src="../bower_components/jquery-mousewheel/jquery.mousewheel.js"></script>
  <script src="../bower_components/mousetrap/mousetrap.js"></script>

I Can download this?

**Comment by dularion** [comment]
Hi, thanks for your question. In order to use the app run `bower install` in the directory. That should take care of installing all dependencies for you! :)

**Comment by dularion** [comment]
I've adjusted the readme to better explain everything: https://github.com/dularion/streama-video-player/blob/master/README.md

**Comment by IZ44KPvP** [comment]
Thanks
